[programs.localnet]
mysolanaapp = "E67Lzkvh2u4PXomXVtvbpUKbMcMHRFDYm5QAem25a2X7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/yihauchen/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
